export type Timezone = {
    region: string
    text: string
    city: string
    offset?: string
}
const timezones: Timezone[] = [
    {
        region: 'Africa',
        text: 'Africa/Abidjan',
        city: 'Abidjan',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Accra',
        city: 'Accra',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Algiers',
        city: 'Algiers',
        offset: '+01:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Bissau',
        city: 'Bissau',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Cairo',
        city: 'Cairo',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Casablanca',
        city: 'Casablanca',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Ceuta',
        city: 'Ceuta',
        offset: '+01:00',
    },
    {
        region: 'Africa',
        text: 'Africa/El_Aaiun',
        city: 'El Aaiun',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Johannesburg',
        city: 'Johannesburg',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Juba',
        city: 'Juba',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Khartoum',
        city: 'Khartoum',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Lagos',
        city: 'Lagos',
        offset: '+01:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Maputo',
        city: 'Maputo',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Monrovia',
        city: 'Monrovia',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Nairobi',
        city: 'Nairobi',
        offset: '+03:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Ndjamena',
        city: 'Ndjamena',
        offset: '+01:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Sao_Tome',
        city: 'Sao Tome',
        offset: '+00:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Tripoli',
        city: 'Tripoli',
        offset: '+02:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Tunis',
        city: 'Tunis',
        offset: '+01:00',
    },
    {
        region: 'Africa',
        text: 'Africa/Windhoek',
        city: 'Windhoek',
        offset: '+02:00',
    },
    {
        region: 'America',
        text: 'America/Adak',
        city: 'Adak',
        offset: '-10:00',
    },
    {
        region: 'America',
        text: 'America/Anchorage',
        city: 'Anchorage',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/Araguaina',
        city: 'Araguaina',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Buenos_Aires',
        city: 'Buenos Aires',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Catamarca',
        city: 'Catamarca',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Cordoba',
        city: 'Cordoba',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Jujuy',
        city: 'Jujuy',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/La_Rioja',
        city: 'La Rioja',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Mendoza',
        city: 'Mendoza',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Rio_Gallegos',
        city: 'Rio Gallegos',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Salta',
        city: 'Salta',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/San_Juan',
        city: 'San Juan',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/San_Luis',
        city: 'San Luis',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Tucuman',
        city: 'Tucuman',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Argentina/Ushuaia',
        city: 'Ushuaia',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Asuncion',
        city: 'Asuncion',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Atikokan',
        city: 'Atikokan',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Bahia',
        city: 'Bahia',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Bahia_Banderas',
        city: 'Bahia Banderas',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Barbados',
        city: 'Barbados',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Belem',
        city: 'Belem',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Belize',
        city: 'Belize',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Blanc-Sablon',
        city: 'Blanc-Sablon',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Boa_Vista',
        city: 'Boa Vista',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Bogota',
        city: 'Bogota',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Boise',
        city: 'Boise',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Cambridge_Bay',
        city: 'Cambridge Bay',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Campo_Grande',
        city: 'Campo Grande',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Cancun',
        city: 'Cancun',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Caracas',
        city: 'Caracas',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Cayenne',
        city: 'Cayenne',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Chicago',
        city: 'Chicago',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Chihuahua',
        city: 'Chihuahua',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Costa_Rica',
        city: 'Costa Rica',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Creston',
        city: 'Creston',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Cuiaba',
        city: 'Cuiaba',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Curacao',
        city: 'Curacao',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Danmarkshavn',
        city: 'Danmarkshavn',
        offset: '+00:00',
    },
    {
        region: 'America',
        text: 'America/Dawson',
        city: 'Dawson',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Dawson_Creek',
        city: 'Dawson Creek',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Denver',
        city: 'Denver',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Detroit',
        city: 'Detroit',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Edmonton',
        city: 'Edmonton',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Eirunepe',
        city: 'Eirunepe',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/El_Salvador',
        city: 'El Salvador',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Fort_Nelson',
        city: 'Fort Nelson',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Fortaleza',
        city: 'Fortaleza',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Glace_Bay',
        city: 'Glace Bay',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Godthab',
        city: 'Godthab',
    },
    {
        region: 'America',
        text: 'America/Goose_Bay',
        city: 'Goose Bay',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Grand_Turk',
        city: 'Grand Turk',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Guatemala',
        city: 'Guatemala',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Guayaquil',
        city: 'Guayaquil',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Guyana',
        city: 'Guyana',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Halifax',
        city: 'Halifax',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Havana',
        city: 'Havana',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Hermosillo',
        city: 'Hermosillo',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Indianapolis',
        city: 'Indianapolis',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Knox',
        city: 'Knox',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Marengo',
        city: 'Marengo',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Petersburg',
        city: 'Petersburg',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Tell_City',
        city: 'Tell City',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Vevay',
        city: 'Vevay',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Vincennes',
        city: 'Vincennes',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Indiana/Winamac',
        city: 'Winamac',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Inuvik',
        city: 'Inuvik',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Iqaluit',
        city: 'Iqaluit',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Jamaica',
        city: 'Jamaica',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Juneau',
        city: 'Juneau',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/Kentucky/Louisville',
        city: 'Louisville',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Kentucky/Monticello',
        city: 'Monticello',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/La_Paz',
        city: 'La Paz',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Lima',
        city: 'Lima',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Los_Angeles',
        city: 'Los Angeles',
        offset: '-08:00',
    },
    {
        region: 'America',
        text: 'America/Maceio',
        city: 'Maceio',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Managua',
        city: 'Managua',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Manaus',
        city: 'Manaus',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Martinique',
        city: 'Martinique',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Matamoros',
        city: 'Matamoros',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Mazatlan',
        city: 'Mazatlan',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Menominee',
        city: 'Menominee',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Merida',
        city: 'Merida',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Metlakatla',
        city: 'Metlakatla',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/Mexico_City',
        city: 'Mexico City',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Miquelon',
        city: 'Miquelon',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Moncton',
        city: 'Moncton',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Monterrey',
        city: 'Monterrey',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Montevideo',
        city: 'Montevideo',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Nassau',
        city: 'Nassau',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/New_York',
        city: 'New York',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Nipigon',
        city: 'Nipigon',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Nome',
        city: 'Nome',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/Noronha',
        city: 'Noronha',
        offset: '-02:00',
    },
    {
        region: 'America',
        text: 'America/North_Dakota/Beulah',
        city: 'Beulah, ND',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/North_Dakota/Center',
        city: 'Center, ND',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/North_Dakota/New_Salem',
        city: 'New Salem, ND',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Ojinaga',
        city: 'Ojinaga',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Panama',
        city: 'Panama',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Pangnirtung',
        city: 'Pangnirtung',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Paramaribo',
        city: 'Paramaribo',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Phoenix',
        city: 'Phoenix',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Port-au-Prince',
        city: 'Port-au-Prince',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Port_of_Spain',
        city: 'Port of Spain',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Porto_Velho',
        city: 'Porto Velho',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Puerto_Rico',
        city: 'Puerto Rico',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Punta_Arenas',
        city: 'Punta Arenas',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Rainy_River',
        city: 'Rainy River',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Rankin_Inlet',
        city: 'Rankin Inlet',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Recife',
        city: 'Recife',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Regina',
        city: 'Regina',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Resolute',
        city: 'Resolute',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Rio_Branco',
        city: 'Rio Branco',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Santarem',
        city: 'Santarem',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Santiago',
        city: 'Santiago',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Santo_Domingo',
        city: 'Santo Domingo',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Sao_Paulo',
        city: 'Sao Paulo',
        offset: '-03:00',
    },
    {
        region: 'America',
        text: 'America/Scoresbysund',
        city: 'Scoresbysund',
        offset: '-01:00',
    },
    {
        region: 'America',
        text: 'America/Sitka',
        city: 'Sitka',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/St_Johns',
        city: 'St Johns',
        offset: '-04:30',
    },
    {
        region: 'America',
        text: 'America/Swift_Current',
        city: 'Swift Current',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Tegucigalpa',
        city: 'Tegucigalpa',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Thule',
        city: 'Thule',
        offset: '-04:00',
    },
    {
        region: 'America',
        text: 'America/Thunder_Bay',
        city: 'Thunder Bay',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Tijuana',
        city: 'Tijuana',
        offset: '-08:00',
    },
    {
        region: 'America',
        text: 'America/Toronto',
        city: 'Toronto',
        offset: '-05:00',
    },
    {
        region: 'America',
        text: 'America/Vancouver',
        city: 'Vancouver',
        offset: '-08:00',
    },
    {
        region: 'America',
        text: 'America/Whitehorse',
        city: 'Whitehorse',
        offset: '-07:00',
    },
    {
        region: 'America',
        text: 'America/Winnipeg',
        city: 'Winnipeg',
        offset: '-06:00',
    },
    {
        region: 'America',
        text: 'America/Yakutat',
        city: 'Yakutat',
        offset: '-09:00',
    },
    {
        region: 'America',
        text: 'America/Yellowknife',
        city: 'Yellowknife',
        offset: '-07:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Casey',
        city: 'Casey',
        offset: '+11:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Davis',
        city: 'Davis',
        offset: '+07:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Macquarie',
        city: 'Macquarie',
        offset: '+10:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Mawson',
        city: 'Mawson',
        offset: '+05:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Palmer',
        city: 'Palmer',
        offset: '-03:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Rothera',
        city: 'Rothera',
        offset: '-03:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Syowa',
        city: 'Syowa',
        offset: '+03:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Troll',
        city: 'Troll',
        offset: '+00:00',
    },
    {
        region: 'Antarctica',
        text: 'Antarctica/Vostok',
        city: 'Vostok',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Almaty',
        city: 'Almaty',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Amman',
        city: 'Amman',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Anadyr',
        city: 'Anadyr',
        offset: '+12:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Aqtau',
        city: 'Aqtau',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Aqtobe',
        city: 'Aqtobe',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Ashgabat',
        city: 'Ashgabat',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Atyrau',
        city: 'Atyrau',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Baghdad',
        city: 'Baghdad',
        offset: '+03:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Baku',
        city: 'Baku',
        offset: '+04:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Bangkok',
        city: 'Bangkok',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Barnaul',
        city: 'Barnaul',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Beirut',
        city: 'Beirut',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Bishkek',
        city: 'Bishkek',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Brunei',
        city: 'Brunei',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Manila',
        city: 'Cebu',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Chita',
        city: 'Chita',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Choibalsan',
        city: 'Choibalsan',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Colombo',
        city: 'Colombo',
        offset: '+05:30',
    },
    {
        region: 'Asia',
        text: 'Asia/Damascus',
        city: 'Damascus',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Dhaka',
        city: 'Dhaka',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Dili',
        city: 'Dili',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Dubai',
        city: 'Dubai',
        offset: '+04:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Dushanbe',
        city: 'Dushanbe',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Famagusta',
        city: 'Famagusta',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Gaza',
        city: 'Gaza',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Hebron',
        city: 'Hebron',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Ho_Chi_Minh',
        city: 'Ho Chi Minh',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Hong_Kong',
        city: 'Hong Kong',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Hovd',
        city: 'Hovd',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Irkutsk',
        city: 'Irkutsk',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Jakarta',
        city: 'Jakarta',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Jayapura',
        city: 'Jayapura',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Jerusalem',
        city: 'Jerusalem',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Kabul',
        city: 'Kabul',
        offset: '+04:30',
    },
    {
        region: 'Asia',
        text: 'Asia/Kamchatka',
        city: 'Kamchatka',
        offset: '+12:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Karachi',
        city: 'Karachi',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Kathmandu',
        city: 'Kathmandu',
        offset: '+05:45',
    },
    {
        region: 'Asia',
        text: 'Asia/Khandyga',
        city: 'Khandyga',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Kolkata',
        city: 'Kolkata',
        offset: '+05:30',
    },
    {
        region: 'Asia',
        text: 'Asia/Krasnoyarsk',
        city: 'Krasnoyarsk',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Kuala_Lumpur',
        city: 'Kuala Lumpur',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Kuching',
        city: 'Kuching',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Macau',
        city: 'Macau',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Magadan',
        city: 'Magadan',
        offset: '+11:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Makassar',
        city: 'Makassar',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Manila',
        city: 'Manila',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Nicosia',
        city: 'Nicosia',
        offset: '+02:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Novokuznetsk',
        city: 'Novokuznetsk',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Novosibirsk',
        city: 'Novosibirsk',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Omsk',
        city: 'Omsk',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Oral',
        city: 'Oral',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Pontianak',
        city: 'Pontianak',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Pyongyang',
        city: 'Pyongyang',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Qatar',
        city: 'Qatar',
        offset: '+03:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Qyzylorda',
        city: 'Qyzylorda',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Riyadh',
        city: 'Riyadh',
        offset: '+03:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Sakhalin',
        city: 'Sakhalin',
        offset: '+11:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Samarkand',
        city: 'Samarkand',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Seoul',
        city: 'Seoul',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Shanghai',
        city: 'Shanghai',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Singapore',
        city: 'Singapore',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Srednekolymsk',
        city: 'Srednekolymsk',
        offset: '+11:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Taipei',
        city: 'Taipei',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Tashkent',
        city: 'Tashkent',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Tbilisi',
        city: 'Tbilisi',
        offset: '+04:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Tehran',
        city: 'Tehran',
        offset: '+03:30',
    },
    {
        region: 'Asia',
        text: 'Asia/Thimphu',
        city: 'Thimphu',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Tokyo',
        city: 'Tokyo',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Tomsk',
        city: 'Tomsk',
        offset: '+07:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Ulaanbaatar',
        city: 'Ulaanbaatar',
        offset: '+08:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Urumqi',
        city: 'Urumqi',
        offset: '+06:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Ust-Nera',
        city: 'Ust-Nera',
        offset: '+10:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Vladivostok',
        city: 'Vladivostok',
        offset: '+10:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Yakutsk',
        city: 'Yakutsk',
        offset: '+09:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Yangon',
        city: 'Yangon',
        offset: '+06:30',
    },
    {
        region: 'Asia',
        text: 'Asia/Yekaterinburg',
        city: 'Yekaterinburg',
        offset: '+05:00',
    },
    {
        region: 'Asia',
        text: 'Asia/Yerevan',
        city: 'Yerevan',
        offset: '+04:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Azores',
        city: 'Azores',
        offset: '-01:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Bermuda',
        city: 'Bermuda',
        offset: '-04:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Canary',
        city: 'Canary',
        offset: '+00:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Cape_Verde',
        city: 'Cape Verde',
        offset: '-01:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Faroe',
        city: 'Faroe',
        offset: '+00:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Madeira',
        city: 'Madeira',
        offset: '+00:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Reykjavik',
        city: 'Reykjavik',
        offset: '+00:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/South_Georgia',
        city: 'South Georgia',
        offset: '-02:00',
    },
    {
        region: 'Atlantic',
        text: 'Atlantic/Stanley',
        city: 'Stanley',
        offset: '-03:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Adelaide',
        city: 'Adelaide',
        offset: '+09:30',
    },
    {
        region: 'Australia',
        text: 'Australia/Brisbane',
        city: 'Brisbane',
        offset: '+10:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Broken_Hill',
        city: 'Broken Hill',
        offset: '+09:30',
    },
    {
        region: 'Australia',
        text: 'Australia/Currie',
        city: 'Currie',
        offset: '+10:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Darwin',
        city: 'Darwin',
        offset: '+09:30',
    },
    {
        region: 'Australia',
        text: 'Australia/Eucla',
        city: 'Eucla',
        offset: '+08:45',
    },
    {
        region: 'Australia',
        text: 'Australia/Hobart',
        city: 'Hobart',
        offset: '+10:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Lindeman',
        city: 'Lindeman',
        offset: '+10:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Lord_Howe',
        city: 'Lord Howe',
        offset: '+10:30',
    },
    {
        region: 'Australia',
        text: 'Australia/Melbourne',
        city: 'Melbourne',
        offset: '+10:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Perth',
        city: 'Perth',
        offset: '+08:00',
    },
    {
        region: 'Australia',
        text: 'Australia/Sydney',
        city: 'Sydney',
        offset: '+10:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Amsterdam',
        city: 'Amsterdam',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Andorra',
        city: 'Andorra',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Astrakhan',
        city: 'Astrakhan',
        offset: '+04:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Athens',
        city: 'Athens',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Belgrade',
        city: 'Belgrade',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Berlin',
        city: 'Berlin',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Brussels',
        city: 'Brussels',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Bucharest',
        city: 'Bucharest',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Budapest',
        city: 'Budapest',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Chisinau',
        city: 'Chisinau',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Copenhagen',
        city: 'Copenhagen',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Dublin',
        city: 'Dublin',
        offset: '+00:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Gibraltar',
        city: 'Gibraltar',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Helsinki',
        city: 'Helsinki',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Istanbul',
        city: 'Istanbul',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Kaliningrad',
        city: 'Kaliningrad',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Kiev',
        city: 'Kiev',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Kirov',
        city: 'Kirov',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Lisbon',
        city: 'Lisbon',
        offset: '+00:00',
    },
    {
        region: 'Europe',
        text: 'Europe/London',
        city: 'London',
        offset: '+00:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Luxembourg',
        city: 'Luxembourg',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Madrid',
        city: 'Madrid',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Malta',
        city: 'Malta',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Minsk',
        city: 'Minsk',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Monaco',
        city: 'Monaco',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Moscow',
        city: 'Moscow',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Oslo',
        city: 'Oslo',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Paris',
        city: 'Paris',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Prague',
        city: 'Prague',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Riga',
        city: 'Riga',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Rome',
        city: 'Rome',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Samara',
        city: 'Samara',
        offset: '+04:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Saratov',
        city: 'Saratov',
        offset: '+04:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Simferopol',
        city: 'Simferopol',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Sofia',
        city: 'Sofia',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Stockholm',
        city: 'Stockholm',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Tallinn',
        city: 'Tallinn',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Tirane',
        city: 'Tirane',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Ulyanovsk',
        city: 'Ulyanovsk',
        offset: '+04:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Uzhgorod',
        city: 'Uzhgorod',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Vienna',
        city: 'Vienna',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Vilnius',
        city: 'Vilnius',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Volgograd',
        city: 'Volgograd',
        offset: '+03:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Warsaw',
        city: 'Warsaw',
        offset: '+01:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Zaporozhye',
        city: 'Zaporozhye',
        offset: '+02:00',
    },
    {
        region: 'Europe',
        text: 'Europe/Zurich',
        city: 'Zurich',
        offset: '+01:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Chagos',
        city: 'Chagos',
        offset: '+06:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Christmas',
        city: 'Christmas',
        offset: '+07:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Cocos',
        city: 'Cocos',
        offset: '+06:30',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Kerguelen',
        city: 'Kerguelen',
        offset: '+05:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Mahe',
        city: 'Mahe',
        offset: '+04:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Maldives',
        city: 'Maldives',
        offset: '+05:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Mauritius',
        city: 'Mauritius',
        offset: '+04:00',
    },
    {
        region: 'Indian Ocean',
        text: 'Indian/Reunion',
        city: 'Reunion',
        offset: '+04:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Apia',
        city: 'Apia',
        offset: '+13:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Auckland',
        city: 'Auckland',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Bougainville',
        city: 'Bougainville',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Chatham',
        city: 'Chatham',
        offset: '+12:45',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Chuuk',
        city: 'Chuuk',
        offset: '+10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Easter',
        city: 'Easter',
        offset: '-06:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Efate',
        city: 'Efate',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Enderbury',
        city: 'Enderbury',
        offset: '+13:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Fakaofo',
        city: 'Fakaofo',
        offset: '+13:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Fiji',
        city: 'Fiji',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Funafuti',
        city: 'Funafuti',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Galapagos',
        city: 'Galapagos',
        offset: '-06:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Gambier',
        city: 'Gambier',
        offset: '-09:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Guadalcanal',
        city: 'Guadalcanal',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Guam',
        city: 'Guam',
        offset: '+10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Honolulu',
        city: 'Honolulu',
        offset: '-10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Kiritimati',
        city: 'Kiritimati',
        offset: '+14:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Kosrae',
        city: 'Kosrae',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Kwajalein',
        city: 'Kwajalein',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Majuro',
        city: 'Majuro',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Marquesas',
        city: 'Marquesas',
        offset: '-10:30',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Nauru',
        city: 'Nauru',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Niue',
        city: 'Niue',
        offset: '-11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Norfolk',
        city: 'Norfolk',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Noumea',
        city: 'Noumea',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Pago_Pago',
        city: 'Pago Pago',
        offset: '-11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Palau',
        city: 'Palau',
        offset: '+09:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Pitcairn',
        city: 'Pitcairn',
        offset: '-08:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Pohnpei',
        city: 'Pohnpei',
        offset: '+11:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Port_Moresby',
        city: 'Port Moresby',
        offset: '+10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Rarotonga',
        city: 'Rarotonga',
        offset: '-10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Tahiti',
        city: 'Tahiti',
        offset: '-10:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Tarawa',
        city: 'Tarawa',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Tongatapu',
        city: 'Tongatapu',
        offset: '+13:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Wake',
        city: 'Wake',
        offset: '+12:00',
    },
    {
        region: 'Pacific',
        text: 'Pacific/Wallis',
        city: 'Wallis',
        offset: '+12:00',
    },
]

export default timezones
