export const mockGetTransalations = {
    data: {
        attributes: {
            drupal_internal__nid: 3,
            drupal_internal__vid: 24,
            langcode: 'en',
            revision_timestamp: '2021-10-05T10:36:10+00:00',
            revision_log: null,
            status: true,
            title: 'Signup Modal',
            created: '2021-10-05T03:06:44+00:00',
            changed: '2021-10-05T10:36:10+00:00',
            promote: true,
            sticky: false,
            default_langcode: true,
            revision_translation_affected: true,
            path: {
                alias: null,
                pid: null,
                langcode: 'en',
            },
            field_en_us: [
                {
                    key: 'title_bar',
                    description: '',
                    value: 'Sign up',
                    format: 'plain_text',
                    processed: '<p>Sign up</p>\n',
                },
                {
                    key: 'promotional_header',
                    description: '',
                    value: 'Join us today as an early adopter and receive 50% off your first 3 months with AOT!',
                    format: 'plain_text',
                    processed:
                        '<p>Join us today as an early adopter and receive 50% off your first 3 months with AOT!</p>\n',
                },
                {
                    key: 'signup_button',
                    description: '',
                    value: 'Sign up',
                    format: 'plain_text',
                    processed: '<p>Sign up</p>\n',
                },
                {
                    key: 'email_address_label',
                    description: '',
                    value: 'Email address',
                    format: 'plain_text',
                    processed: '<p>Email address</p>\n',
                },
                {
                    key: 'password_label',
                    description: '',
                    value: 'Password',
                    format: 'plain_text',
                    processed: '<p>Password</p>\n',
                },
                {
                    key: 'first_name_label',
                    description: '',
                    value: 'First name',
                    format: 'plain_text',
                    processed: '<p>First name</p>\n',
                },
                {
                    key: 'last_name_label',
                    description: '',
                    value: 'Last name',
                    format: 'plain_text',
                    processed: '<p>Last name</p>\n',
                },
                {
                    key: 'business_name_label',
                    description: '',
                    value: 'Business name',
                    format: 'plain_text',
                    processed: '<p>Business name</p>\n',
                },
            ],
            field_zh_cn: [
                {
                    key: 'title_bar',
                    description: '',
                    value: '报名',
                    format: 'plain_text',
                    processed: '<p>报名</p>\n',
                },
                {
                    key: 'promotional_header',
                    description: '',
                    value: '立即加入我们，成为早期采用者，使用 AOT 即可享受前 3 个月的 50% 折扣！',
                    format: 'plain_text',
                    processed:
                        '<p>立即加入我们，成为早期采用者，使用 AOT 即可享受前 3 个月的 50% 折扣！</p>\n',
                },
                {
                    key: 'signup_button',
                    description: '',
                    value: '马 上报名',
                    format: 'plain_text',
                    processed: '<p>马 上报名</p>\n',
                },
                {
                    key: 'email_address_label',
                    description: '',
                    value: '邮箱地址',
                    format: 'plain_text',
                    processed: '<p>邮箱地址</p>\n',
                },
                {
                    key: 'password_label',
                    description: '',
                    value: '密码',
                    format: 'plain_text',
                    processed: '<p>密码</p>\n',
                },
                {
                    key: 'first_name_label',
                    description: '',
                    value: '名',
                    format: 'plain_text',
                    processed: '<p>名</p>\n',
                },
                {
                    key: 'last_name_label',
                    description: '',
                    value: '姓',
                    format: 'plain_text',
                    processed: '<p>姓</p>\n',
                },
                {
                    key: 'business_name_label',
                    description: '',
                    value: '企业名称',
                    format: 'plain_text',
                    processed: '<p>企业名称</p>\n',
                },
            ],
        },
    },
}
