export const mockGetTransalations = {
    data: {
        field_en_us: [
            {
                key: 'login_button',
                description: '',
                value: 'Login',
                format: 'plain_text',
                processed: '<p>Login</p>\n',
            },
            {
                key: 'email_address_label',
                description: '',
                value: 'E-mail address',
                format: 'plain_text',
                processed: '<p>E-mail address</p>\n',
            },
            {
                key: 'forgot_password_link',
                description: '',
                value: 'Forgot your password?',
                format: 'plain_text',
                processed: '<p>Forgot your password?</p>\n',
            },
            {
                key: 'password_label',
                description: '',
                value: 'Password',
                format: 'plain_text',
                processed: '<p>Password</p>\n',
            },
            {
                key: 'login_title',
                description: '',
                value: 'Login',
                format: 'plain_text',
                processed: '<p>Login</p>\n',
            },
            {
                key: 'send_reset_code_button',
                description: '',
                value: 'Send reset code',
                format: 'plain_text',
                processed: '<p>Send reset code</p>\n',
            },
        ],
        field_zh_cn: [
            {
                key: 'login_button',
                description: '',
                value: '登录',
                format: 'plain_text',
                processed: '<p>登录</p>\n',
            },
            {
                key: 'email_address_label',
                description: '',
                value: '邮件地址',
                format: 'plain_text',
                processed: '<p>邮件地址</p>\n',
            },
            {
                key: 'password_label',
                description: '',
                value: '密码',
                format: 'plain_text',
                processed: '<p>密码</p>\n',
            },
            {
                key: 'forgot_password_link',
                description: '',
                value: '忘记密码',
                format: 'plain_text',
                processed: '<p>忘记密码</p>\n',
            },
            {
                key: 'login_title',
                description: '',
                value: '登录',
                format: 'plain_text',
                processed: '<p>登录</p>\n',
            },
            {
                key: 'send_reset_code_button',
                description: '',
                value: '发送重置代码',
                format: 'plain_text',
                processed: '<p>发送重置代码</p>\n',
            },
        ],
    },
}
