export const mockGetTransalations = {
    data: {
        attributes: {
            drupal_internal__nid: 5,
            drupal_internal__vid: 33,
            langcode: 'en',
            revision_timestamp: '2021-10-18T01:50:47+00:00',
            revision_log: null,
            status: true,
            title: 'About Us',
            created: '2021-10-15T10:32:30+00:00',
            changed: '2021-10-18T01:50:47+00:00',
            promote: true,
            sticky: false,
            default_langcode: true,
            revision_translation_affected: true,
            path: {
                alias: null,
                pid: null,
                langcode: 'en',
            },
            field_en_us: [
                {
                    key: 'banner_title',
                    description: '',
                    value: 'About Us',
                    format: 'plain_text',
                    processed: '<p>About Us</p>\n',
                },
                {
                    key: 'section_1_title',
                    description: '',
                    value: 'Best-in-class Scheduling & Business Management Platform +',
                    format: 'plain_text',
                    processed:
                        '<p>Best-in-class Scheduling &amp; Business Management Platform +</p>\n',
                },
                {
                    key: 'section_1_cofounder',
                    description: '',
                    value: "Hi I'm Greg, the co-founder",
                    format: 'plain_text',
                    processed: '<p>Hi I&#039;m Greg, the co-founder</p>\n',
                },
                {
                    key: 'section_1_story',
                    description: '',
                    value: 'Our story',
                    format: 'plain_text',
                    processed: '<p>Our story</p>\n',
                },
                {
                    key: 'section_1_how_it_started',
                    description: '',
                    value: 'How it started',
                    format: 'plain_text',
                    processed: '<p>How it started</p>\n',
                },
                {
                    key: 'section_1_story_paragraph',
                    description: '',
                    value: 'We have been in the market, using various market-ready scheduling software, to help with my wife and her team manage her classes. After realising that market-ready softwares not being intuitive and actually helpful, I used existing softwares as a foundation, and built so much customization, it became a nightmare to support and maintain, but at the same time it transformed the system we were using from a basic booking portal into a fully-fledged scheduling and small business management platform, and that added a ton of value for our business.\r\n',
                    format: 'plain_text',
                    processed:
                        '<p>We have been in the market, using various market-ready scheduling software, to help with my wife and her team manage her classes. After realising that market-ready softwares not being intuitive and actually helpful, I used existing softwares as a foundation, and built so much customization, it became a nightmare to support and maintain, but at the same time it transformed the system we were using from a basic booking portal into a fully-fledged scheduling and small business management platform, and that added a ton of value for our business.</p>\n',
                },
                {
                    key: 'section_1_mission',
                    description: '',
                    value: 'Our mission',
                    format: 'plain_text',
                    processed: '<p>Our mission</p>\n',
                },
                {
                    key: 'section_1_exist',
                    description: '',
                    value: 'Why We Exist',
                    format: 'plain_text',
                    processed: '<p>Why We Exist</p>\n',
                },
                {
                    key: 'section_1_exist_paragraph',
                    description: '',
                    value: 'Despite all the customization, the application was limited in its functions,\r\nand couldn’t meet our business needs. It was then we realise that we have\r\nthe know how and knowledge to build a solution inside out, fit for the\r\nindustry.\r\n',
                    format: 'plain_text',
                    processed:
                        '<p>Despite all the customization, the application was limited in its functions,<br />\nand couldn’t meet our business needs. It was then we realise that we have<br />\nthe know how and knowledge to build a solution inside out, fit for the<br />\nindustry.</p>\n',
                },
                {
                    key: 'section_2_title_1',
                    description: '',
                    value: '8 Months &',
                    format: 'plain_text',
                    processed: '<p>8 Months &amp;</p>\n',
                },
                {
                    key: 'section_2_title_2',
                    description: '',
                    value: '4 Days Later',
                    format: 'plain_text',
                    processed: '<p>4 Days Later</p>\n',
                },
                {
                    key: 'section_2_paragraph',
                    description: '',
                    value: 'led to the creation of AOT, a customisable\r\nintegrated software that offers an all-inclusive suite, including payroll\r\ncalculation and package management. It has helped us streamlined the\r\nprocess and helped us in franchising our dance and yoga business.',
                    format: 'plain_text',
                    processed:
                        '<p>led to the creation of AOT, a customisable<br />\nintegrated software that offers an all-inclusive suite, including payroll<br />\ncalculation and package management. It has helped us streamlined the<br />\nprocess and helped us in franchising our dance and yoga business.</p>\n',
                },
                {
                    key: 'section_3_title',
                    description: '',
                    value: 'Values We Live By',
                    format: 'plain_text',
                    processed: '<p>Values We Live By</p>\n',
                },
                {
                    key: 'section_3_subtitle',
                    description: '',
                    value: 'Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. ',
                    format: 'plain_text',
                    processed:
                        '<p>Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.</p>\n',
                },
                {
                    key: 'section_3_item_1_title',
                    description: '',
                    value: 'Detail-oriented',
                    format: 'plain_text',
                    processed: '<p>Detail-oriented</p>\n',
                },
                {
                    key: 'section_3_item_1_body',
                    description: '',
                    value: 'Help our customers by adding the small details and finishing touches that set Always On Time apart from the crowd',
                    format: 'plain_text',
                    processed:
                        '<p>Help our customers by adding the small details and finishing touches that set Always On Time apart from the crowd</p>\n',
                },
                {
                    key: 'section_3_item_2_title',
                    description: '',
                    value: 'Genuine and Helpful',
                    format: 'plain_text',
                    processed: '<p>Genuine and Helpful</p>\n',
                },
                {
                    key: 'section_3_item_2_body',
                    description: '',
                    value: 'We do the little things that help our customers be on time and run their business better',
                    format: 'plain_text',
                    processed:
                        '<p>We do the little things that help our customers be on time and run their business better</p>\n',
                },
                {
                    key: 'section_3_item_3_title',
                    description: '',
                    value: 'Methodolical',
                    format: 'plain_text',
                    processed: '<p>Methodolical</p>\n',
                },
                {
                    key: 'section_3_item_3_body',
                    description: '',
                    value: 'Take a detailed, structured, and reasoned approach to everything we do',
                    format: 'plain_text',
                    processed:
                        '<p>Take a detailed, structured, and reasoned approach to everything we do</p>\n',
                },
                {
                    key: 'section_3_item_4_title',
                    description: '',
                    value: 'Simple and Intuitive',
                    format: 'plain_text',
                    processed: '<p>Simple and Intuitive</p>\n',
                },
                {
                    key: 'section_3_item_4_body',
                    description: '',
                    value: 'Our software must be simple enough to be used intuitively by our users',
                    format: 'plain_text',
                    processed:
                        '<p>Our software must be simple enough to be used intuitively by our users</p>\n',
                },
                {
                    key: 'section_4_title',
                    description: '',
                    value: 'We are confident that our solution can help any studio, ',
                    format: 'plain_text',
                    processed:
                        '<p>We are confident that our solution can help any studio,</p>\n',
                },
                {
                    key: 'section_4_subtitle',
                    description: '',
                    value: 'so that you can work smart and save time.',
                    format: 'plain_text',
                    processed:
                        '<p>so that you can work smart and save time.</p>\n',
                },
                {
                    key: 'join_cta_button',
                    description: '',
                    value: 'Join as an early adopter',
                    format: 'plain_text',
                    processed: '<p>Join as an early adopter</p>\n',
                },
            ],
            field_zh_cn: [
                {
                    key: 'banner_title',
                    description: '',
                    value: '关于我们',
                    format: 'plain_text',
                    processed: '<p>关于我们</p>\n',
                },
                {
                    key: 'section_1_title',
                    description: '',
                    value: 'section_1_title',
                    format: 'plain_text',
                    processed: '<p>section_1_title</p>\n',
                },
                {
                    key: 'section_1_cofounder',
                    description: '',
                    value: 'section_1_cofounder',
                    format: 'plain_text',
                    processed: '<p>section_1_cofounder</p>\n',
                },
                {
                    key: 'section_1_story',
                    description: '',
                    value: 'section_1_story',
                    format: 'plain_text',
                    processed: '<p>section_1_story</p>\n',
                },
                {
                    key: 'section_1_how_it_started',
                    description: '',
                    value: 'section_1_how_it_started',
                    format: 'plain_text',
                    processed: '<p>section_1_how_it_started</p>\n',
                },
                {
                    key: 'section_1_story_paragraph',
                    description: '',
                    value: '',
                    format: 'plain_text',
                    processed: '',
                },
                {
                    key: 'section_1_mission',
                    description: '',
                    value: 'section_1_mission',
                    format: 'plain_text',
                    processed: '<p>section_1_mission</p>\n',
                },
                {
                    key: 'section_1_exist',
                    description: '',
                    value: 'section_1_exist',
                    format: 'plain_text',
                    processed: '<p>section_1_exist</p>\n',
                },
                {
                    key: 'section_1_story_paragraph',
                    description: '',
                    value: 'section_1_story_paragraph',
                    format: 'plain_text',
                    processed: '<p>section_1_story_paragraph</p>\n',
                },
                {
                    key: 'section_1_exist_paragraph',
                    description: '',
                    value: 'section_1_exist_paragraph',
                    format: 'plain_text',
                    processed: '<p>section_1_exist_paragraph</p>\n',
                },
                {
                    key: 'section_2_title_1',
                    description: '',
                    value: 'section_2_title_1',
                    format: 'plain_text',
                    processed: '<p>section_2_title_1</p>\n',
                },
                {
                    key: 'section_2_title_2',
                    description: '',
                    value: 'section_2_title_2',
                    format: 'plain_text',
                    processed: '<p>section_2_title_2</p>\n',
                },
                {
                    key: 'section_2_paragraph',
                    description: '',
                    value: 'section_2_paragraph',
                    format: 'plain_text',
                    processed: '<p>section_2_paragraph</p>\n',
                },
            ],
        },
    },
}
